-- 코드를 입력하세요
SELECT 
TO_CHAR(sale.SALES_DATE,'YYYY') as YEAR, EXTRACT(MONTH FROM sale.SALES_DATE) as MONTH, info.GENDER, COUNT(DISTINCT sale.USER_ID) as USERS
FROM USER_INFO info
INNER JOIN ONLINE_SALE sale ON info.USER_ID = sale.USER_ID
WHERE gender IS NOT NULL
GROUP BY TO_CHAR(sale.SALES_DATE,'YYYY'), EXTRACT(MONTH FROM sale.SALES_DATE), info.GENDER
ORDER BY YEAR, MONTH, GENDER;