-- 코드를 입력하세요
SELECT HOUR, COUNT(O.DATETIME) as COUNT
FROM (
    SELECT LEVEL-1 AS HOUR 
    FROM DUAL 
    CONNECT BY LEVEL <= 24
)H LEFT JOIN ANIMAL_OUTS O
ON H.HOUR = TO_CHAR(O.DATETIME,'HH24')
GROUP BY HOUR
ORDER BY HOUR;