-- 코드를 입력하세요
SELECT ugu.USER_ID, ugu.NICKNAME, SUM(ugb.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(ugb.PRICE) >= 700000
ORDER BY TOTAL_SALES;
