-- 코드를 입력하세요

SELECT EXTRACT(MONTH FROM START_DATE) as MONTH, CAR_ID, count(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN 
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE EXTRACT(MONTH FROM START_DATE) between 8 AND 10
    GROUP BY CAR_ID
    HAVING count(*) >= 5 )
AND EXTRACT(MONTH FROM START_DATE) between 8 AND 10
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY EXTRACT(MONTH FROM START_DATE), CAR_ID DESC;