-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM (
    SELECT info.INGREDIENT_TYPE, half.TOTAL_ORDER
    FROM FIRST_HALF half
    INNER JOIN ICECREAM_INFO info ON half.FLAVOR = info.FLAVOR
) c
GROUP BY c.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;